package com.vdn.lampbearer.views;

public enum BlockTypes {
    PLAYER,
    GROUND,
    GRASS,
    ROCK,
    SIMPLE_ZOMBIE,
    H_CLOSED_DOOR,
    V_CLOSED_DOOR,
    OPENED_DOOR,
    UR_CORNER,
    BR_CORNER,
    UL_CORNER,
    BL_CORNER,
    H_WALL,
    H_WALL_THICK,
    V_WALL_THICK,
    FIRST_AID_KIT,
    H_GLASS,
    V_GLASS,
    UNSEEN,
    EMPTY,
    V_WALL_THICK_R_JOINT,
    LAMPPOST,
    LANTERN,
    OIL_BOTTLE,
}
